# Chat Memory API

### mem0 API
GET http://localhost:8080/advisor/memory/mem0/call?query=你好，我是万能的喵。我爱玩魔兽世界&conversation_id=miao
### 信息
GET http://localhost:8080//advisor/memory/mem0/messages?conversation_id=miao
